<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.9.5 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 12304 2009-03-24 12:56:58Z nijel $
 * Date: Tue, 12 May 2009 15:23:32 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (cookie) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4a099470775831.45648628';
?>
