(function($){if(/1\.(0|1|2)\.(0|1|2)/.test($.fn.jquery)||/^1.1/.test($.fn.jquery)){alert("blockUI requires jQuery v1.2.3 or later!  You are using v"+$.fn.jquery);return;}
$.fn._fadeIn=$.fn.fadeIn;$.blockUI=function(_2){install(window,_2);};$.unblockUI=function(_3){remove(window,_3);};$.growlUI=function(_4,_5,_6){var $m=$("<div class=\"growlUI\"></div>");if(_4){$m.append("<h1>"+_4+"</h1>");}
if(_5){$m.append("<h2>"+_5+"</h2>");}
if(_6==undefined){_6=3000;}
$.blockUI({message:$m,fadeIn:700,fadeOut:1000,centerY:false,timeout:_6,showOverlay:false,css:$.blockUI.defaults.growlCSS});};$.fn.block=function(_8){return this.each(function(){if($.css(this,"position")=="static"){this.style.position="relative";}
if($.browser.msie){this.style.zoom=1;}
install(this,_8);});};$.fn.unblock=function(_9){return this.each(function(){remove(this,_9);});};$.blockUI.version=2.16;$.blockUI.defaults={message:"<h1>Please wait...</h1>",css:{padding:0,margin:0,width:"30%",top:"40%",left:"35%",textAlign:"center",color:"#000",border:"3px solid #aaa",backgroundColor:"#fff",cursor:"wait"},overlayCSS:{backgroundColor:"#000",opacity:"0.6"},growlCSS:{width:"350px",top:"10px",left:"",right:"10px",border:"none",padding:"5px",opacity:"0.6",cursor:null,color:"#fff",backgroundColor:"#000","-webkit-border-radius":"10px","-moz-border-radius":"10px"},baseZ:1000,centerX:true,centerY:true,allowBodyStretch:true,constrainTabKey:true,fadeIn:200,fadeOut:400,timeout:0,showOverlay:true,focusInput:true,applyPlatformOpacityRules:true,onUnblock:null,quirksmodeOffsetHack:4};var _a=$.browser.msie&&/MSIE 6.0/.test(navigator.userAgent);var _b=null;var _c=[];function install(el,_e){var _f=(el==window);var msg=_e&&_e.message!==undefined?_e.message:undefined;_e=$.extend({},$.blockUI.defaults,_e||{});_e.overlayCSS=$.extend({},$.blockUI.defaults.overlayCSS,_e.overlayCSS||{});var css=$.extend({},$.blockUI.defaults.css,_e.css||{});msg=msg===undefined?_e.message:msg;if(_f&&_b){remove(window,{fadeOut:0});}
if(msg&&typeof msg!="string"&&(msg.parentNode||msg.jquery)){var _12=msg.jquery?msg[0]:msg;var _13={};$(el).data("blockUI.history",_13);_13.el=_12;_13.parent=_12.parentNode;_13.display=_12.style.display;_13.position=_12.style.position;if(_13.parent){_13.parent.removeChild(_12);}}
var z=_e.baseZ;var _15=($.browser.msie)?$("<iframe class=\"blockUI\" style=\"z-index:"+(z++)+";display:none;border:none;margin:0;padding:0;position:absolute;width:100%;height:100%;top:0;left:0\" src=\"about:blank\"></iframe>"):$("<div class=\"blockUI\" style=\"display:none\"></div>");var _16=$("<div class=\"blockUI blockOverlay\" style=\"z-index:"+(z++)+";display:none;cursor:wait;border:none;margin:0;padding:0;width:100%;height:100%;top:0;left:0\"></div>");var _17=_f?$("<div class=\"blockUI blockMsg blockPage\" style=\"z-index:"+z+";display:none;position:fixed\"></div>"):$("<div class=\"blockUI blockMsg blockElement\" style=\"z-index:"+z+";display:none;position:absolute\"></div>");if(msg){_17.css(css);}
if(!_e.applyPlatformOpacityRules||!($.browser.mozilla&&/Linux/.test(navigator.platform))){_16.css(_e.overlayCSS);}
_16.css("position",_f?"fixed":"absolute");if($.browser.msie){_15.css("opacity","0.0");}
$([_15[0],_16[0],_17[0]]).appendTo(_f?"body":el);var _18=$.browser.msie&&($.browser.version<8||!$.boxModel)&&(!$.boxModel||$("object,embed",_f?null:el).length>0);if(_a||_18&&_17[0].style.setExpression){if(_f&&_e.allowBodyStretch&&$.boxModel){$("html,body").css("height","100%");}
if((_a||!$.boxModel)&&!_f){var t=sz(el,"borderTopWidth"),l=sz(el,"borderLeftWidth");var _1b=t?"(0 - "+t+")":0;var _1c=l?"(0 - "+l+")":0;}
$.each([_15,_16,_17],function(i,o){var s=o[0].style;s.position="absolute";if(i<2){_f?s.setExpression("height","Math.max(document.body.scrollHeight, document.body.offsetHeight) - (jQuery.boxModel?0:"+_e.quirksmodeOffsetHack+") + \"px\""):s.setExpression("height","this.parentNode.offsetHeight + \"px\"");_f?s.setExpression("width","jQuery.boxModel && document.documentElement.clientWidth || document.body.clientWidth + \"px\""):s.setExpression("width","this.parentNode.offsetWidth + \"px\"");if(_1c){s.setExpression("left",_1c);}
if(_1b){s.setExpression("top",_1b);}}else{if(_e.centerY){if(_f){s.setExpression("top","(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + \"px\"");}
s.marginTop=0;}else{if(!_e.centerY&&_f){var top=(_e.css&&_e.css.top)?parseInt(_e.css.top):0;var _21="((document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "+top+") + \"px\"";s.setExpression("top",_21);}}}});}
if(msg){_17.append(msg);if(msg.jquery||msg.nodeType){$(msg).show();}}
if($.browser.msie&&_e.showOverlay){_15.show();}
if(_e.fadeIn){if(_e.showOverlay){_16._fadeIn(_e.fadeIn);}
if(msg){_17.fadeIn(_e.fadeIn);}}else{if(_e.showOverlay){_16.show();}
if(msg){_17.show();}}
bind(1,el,_e);if(_f){_b=_17[0];_c=$(":input:enabled:visible",_b);if(_e.focusInput){setTimeout(focus,20);}}else{center(_17[0],_e.centerX,_e.centerY);}
if(_e.timeout){var to=setTimeout(function(){_f?$.unblockUI(_e):$(el).unblock(_e);},_e.timeout);$(el).data("blockUI.timeout",to);}};function remove(el,_24){var _25=el==window;var $el=$(el);var _27=$el.data("blockUI.history");var to=$el.data("blockUI.timeout");if(to){clearTimeout(to);$el.removeData("blockUI.timeout");}
_24=$.extend({},$.blockUI.defaults,_24||{});bind(0,el,_24);var els=_25?$("body").children().filter(".blockUI"):$(".blockUI",el);if(_25){_b=_c=null;}
if(_24.fadeOut){els.fadeOut(_24.fadeOut);setTimeout(function(){reset(els,_27,_24,el);},_24.fadeOut);}else{reset(els,_27,_24,el);}};function reset(els,_2b,_2c,el){els.each(function(i,o){if(this.parentNode){this.parentNode.removeChild(this);}});if(_2b&&_2b.el){_2b.el.style.display=_2b.display;_2b.el.style.position=_2b.position;if(_2b.parent){_2b.parent.appendChild(_2b.el);}
$(_2b.el).removeData("blockUI.history");}
if(typeof _2c.onUnblock=="function"){_2c.onUnblock(el,_2c);}};function bind(b,el,_32){var _33=el==window,$el=$(el);if(!b&&(_33&&!_b||!_33&&!$el.data("blockUI.isBlocked"))){return;}
if(!_33){$el.data("blockUI.isBlocked",b);}
if(b&&!_32.showOverlay){return;}
var _35="mousedown mouseup keydown keypress";b?$(document).bind(_35,_32,handler):$(document).unbind(_35,handler);};function handler(e){if(e.keyCode&&e.keyCode==9){if(_b&&e.data.constrainTabKey){var els=_c;var fwd=!e.shiftKey&&e.target==els[els.length-1];var _39=e.shiftKey&&e.target==els[0];if(fwd||_39){setTimeout(function(){focus(_39);},10);return false;}}}
if($(e.target).parents("div.blockMsg").length>0){return true;}
return $(e.target).parents().children().filter("div.blockUI").length==0;};function focus(_3a){if(!_c){return;}
var e=_c[_3a===true?_c.length-1:0];if(e){e.focus();}};function center(el,x,y){var p=el.parentNode,s=el.style;var l=((p.offsetWidth-el.offsetWidth)/2)-sz(p,"borderLeftWidth");var t=((p.offsetHeight-el.offsetHeight)/2)-sz(p,"borderTopWidth");if(x){s.left=l>0?(l+"px"):"0";}
if(y){s.top=t>0?(t+"px"):"0";}};function sz(el,p){return parseInt($.css(el,p))||0;};})(jQuery);