<?php
	/**
	 * This view will display the catalog listing generated by paging and sorting
	 * after all search terms have been applied, if any.
	 * 
	 * @package CI_DSSalesRepApp
	 * @subpackage Views-Catalog
	 * @category Views-Catalog
	 * 
	 * @author Nicholas Marshall <njmarshall@ethixsystems.com>
	 * @since 2009-03-19
	 * @version 2009-05-07
	 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
	 */
?>

<table border="0" cellspacing="0" cellpadding="2" align="left" style="font-size:12px; margin-left:8px;">
	<tr>
		<td><a href="/catalog/listingpdf/?<?=$_SERVER['QUERY_STRING']?>"><img src="/img/pdf.gif" border="0" /></a></td>
		<td><a href="/catalog/listingpdf/?<?=$_SERVER['QUERY_STRING']?>">Download This List</a></td>
	</tr>
</table>
<br /><br />
<?=$ListingHTML?>
</td></tr></table>

<table id="ProductDetails" style="display:none" border="0" cellspacing="0" cellpadding="10" width="100%">
	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0" width="100%">
				<tr>
					<td valign="top" width="50%" align="center"><br /><img id="ProductImage" src="" style="max-width:300px; padding-right:20px;" /></td>
					<td valign="top" width="50%">
						<div style="position:absolute; top:5px; right:5px;"><a href="javascript:;" onclick="$.unblockUI();">Close</a></div>
						<br />
						<div id="ProductName" style="font-weight:bold"></div><br />
						<b>Section: </b><div id="ProductSection"></div><br />
						<b>Category: </b><div id="ProductCategory"></div><br />
						<b>Number: </b><div id="ProductNumber"></div><br />
						<b>Stock Price: </b><div id="ProductPrice"></div><br />
						<div id="ProductDescription"></div>
						<br />
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>